# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ElVirus(object):
    def setupUi(self, ElVirus):
        ElVirus.setObjectName("ElVirus")
        ElVirus.resize(800, 600)
        ElVirus.setStyleSheet("")
        self.widget = QtWidgets.QWidget(ElVirus)
        self.widget.setGeometry(QtCore.QRect(680, 0, 120, 31))
        self.widget.setObjectName("widget")
        self.pushButton = QtWidgets.QPushButton(ElVirus)
        self.pushButton.setGeometry(QtCore.QRect(330, 300, 141, 23))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(ElVirus)
        self.textEdit.setGeometry(QtCore.QRect(220, 230, 181, 31))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(ElVirus)
        self.textEdit_2.setGeometry(QtCore.QRect(430, 230, 181, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label = QtWidgets.QLabel(ElVirus)
        self.label.setGeometry(QtCore.QRect(190, 230, 21, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(ElVirus)
        self.label_2.setGeometry(QtCore.QRect(410, 230, 16, 16))
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(ElVirus)
        self.textBrowser.setGeometry(QtCore.QRect(0, 350, 801, 251))
        self.textBrowser.setObjectName("textBrowser")
        self.calendarWidget = QtWidgets.QCalendarWidget(ElVirus)
        self.calendarWidget.setGeometry(QtCore.QRect(0, 10, 312, 183))
        self.calendarWidget.setObjectName("calendarWidget")

        self.retranslateUi(ElVirus)
        QtCore.QMetaObject.connectSlotsByName(ElVirus)

    def retranslateUi(self, ElVirus):
        _translate = QtCore.QCoreApplication.translate
        ElVirus.setWindowTitle(_translate("ElVirus", "ElVirus"))
        self.pushButton.setText(_translate("ElVirus", "Detectar Numeros Primos"))
        self.textEdit.setHtml(_translate("ElVirus", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_2.setHtml(_translate("ElVirus", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label.setText(_translate("ElVirus", "Del"))
        self.label_2.setText(_translate("ElVirus", "AL"))
